version: "3.3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_USER: 'devops'
      MYSQL_ROOT_PASSWORD: 'devops'
      MYSQL_DATABASE: 'filmdb'
      MYSQL_ROOT_HOST: '%'
      MYSQL_PASSWORD: 'devops'
    ports:
      - 3306:3306
    volumes:
      - db:var/lib/mysql
  film_app:
    image: olfarejeb/filmapp
    container_name: filmapp
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.username" : "devops",
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/filmdb?useSSL=false",
        "spring.datasource.password" : "devops"
      }'
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    depends_on:
      - mysqldb
volumes:
  db:
